### ISSUE TITLE
No version available for react-dom 16.9.0-alpha.0

### ISSUE THREAD

**Issue by tnunes** [hot-loader/react-dom#11]
We're currently using `react-dom@16.9.0-alpha.0` due to requirements on the async supporting version of `act` to remove warnings in tests, yet the latest available version of `@hot-loader/react-dom` is for `react-dom@16.8.6`.

Is a version of this module planned for `16.9.0-alpha.0` anytime soon?

Thanks!

**Comment by theKashey** [comment]
O! I was needed async `act` just a few days ago.
We will publish a new version today.

**Comment by tnunes** [comment]
That's great news, thank you!

**Comment by Zache** [comment]
Still no release available?

**Comment by theKashey** [comment]
Released as `16.9.0-alpha.0`, don't forget that it's `@alpha`

**Comment by tnunes** [comment]
Thanks for this 👌
