### ISSUE TITLE
Release React 16.9

### ISSUE THREAD

**Issue by theKashey** [hot-loader/react-dom#14]
It's time @Bnaya!

**Comment by Bnaya** [comment]
I'm taking a look
ATM: 
4.12.10 is failing to patch `react-dom` with the error:
`Error: expected to patch at least 2 files`

Seems like they have changed the content of the package or so

**Comment by Bnaya** [comment]
The files are there, but the patch not patching
They probably have changed things
You can run the code from
https://github.com/hot-loader/react-dom/pull/17/files
With
DEBUG=react-hot-dom-patcher yarn build 

No files are patched ATM

**Comment by Bnaya** [comment]
This is the change in react-dom that make the patch not work: haha :P
```
    if (
      current !== null &&
      (current.elementType === element.type ||
        // Keep this check inline so it only runs on the false path:
        (__DEV__ ? isCompatibleFamilyForHotReloading(current, element) : false))
    ) {
```
https://github.com/facebook/react/blob/c4f0b93703be3d165de78db7a381d6cca2203b2f/packages/react-reconciler/src/ReactChildFiber.js#L401-L406

BTW: seems like isCompatibleFamilyForHotReloading is what this patch is doing. maybe we can just use their mechanism?
https://github.com/facebook/react/blob/c4f0b93703be3d165de78db7a381d6cca2203b2f/packages/react-reconciler/src/ReactFiberHotReloading.js#L131-L140

**Comment by theKashey** [comment]
Give me _tomorrow_ for manual testing

**Comment by theKashey** [comment]
Released!

**Comment by amertak** [comment]
@theKashey Hi, thanks for the release.

Just one thing, that the released version is `16.9.0-4.12.11`, if it's an error or intentional :)

**Comment by zarsky-broad** [comment]
FWIW, the new version number causes a bunch of warnings in the console: 
```
npm WARN <package> requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by theKashey** [comment]
A long version was intentional, and it should be ok. Let me double check.

**Comment by zarsky-broad** [comment]
(We're using aliasing, installing it as `react-dom@npm:@hot-loader/react-dom@...`

**Comment by theKashey** [comment]
Ok, `16.9.0-4.12.11` literally means __prerelease__. We should use `16.9.0+4.12.11` to indicate `16.9.0`+(build)`4.12.11`. Let me read manuals a bit deeper before making a change.

Thank you for a shoutout.

**Comment by Bnaya** [comment]
makes sense

**Comment by Bnaya** [comment]
Link to relevant part on SEMVER docs:
https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions
I personally don't have clear opinion yet how it should be

**Comment by theKashey** [comment]
I've tried sem ver calculator - https://jubianchi.github.io/semver-check/#/^16.9.0/16.9.0%2B4.12.11

`16.9.0+4.12.11` seems to work as expected
<img width="1135" alt="Screen Shot 2019-08-15 at 8 36 14 am" src="https://user-images.githubusercontent.com/582410/63061248-d3db9380-bf37-11e9-8e87-4dca258f0421.png">

However `16.9.0-4.12.11` does not satisfy constraints.
<img width="1136" alt="Screen Shot 2019-08-15 at 8 36 06 am" src="https://user-images.githubusercontent.com/582410/63061249-d3db9380-bf37-11e9-8d84-c549a4c474a3.png">

I __hope__ that `build` number would work as expected on the next update, ie for `16.9.0+4.12.12`, but in anycase, I could just deprecate the old one.

So - our life is a big adventure! Publishing.....

**Comment by theKashey** [comment]
😅 It's for `npm` `16.9.0` even if a version is a bit more concrete - https://unpkg.com/@hot-loader/react-dom@16.9.0/package.json, https://www.npmjs.com/package/@hot-loader/react-dom/v/16.9.0.

I'll create a dummy package and check how to handle it.
