### ISSUE TITLE
When aliasing react-dom to this package, react-apollo fails

### ISSUE THREAD

**Issue by kitze** [hot-loader/react-dom#2]
When using the alias with react-app-rewired, react-apollo starts complaining that 'react-dom/server' cannot be resolved.

Any ideas what can be done?

Thanks

**Comment by theKashey** [comment]
That's my bad - I didn't port "server", only client stuff

**Comment by theKashey** [comment]
`@hot-loader/react-dom@16.7.0-alpha.2.3` now is a full clone of `react-dom`, just a few things patched on the fly.

**Comment by theKashey** [comment]
👍

**Comment by bertho-zero** [comment]
![image](https://user-images.githubusercontent.com/8525267/79578835-0e995b00-80c7-11ea-9d2c-d44358e612a7.png)

I am using version 16.13.0 and I got this error during the webpack build.

I tried the alias Webpack but also Yarn, nothing helps, I am forced to remove the react-dom patch for now.

A require of `react-dom` works but not `react-dom/server`

**Comment by bertho-zero** [comment]
The problem comes from webpack aliases, making an alias for `react-dom` is not enough, that works fine:

```js
'react-dom/server': require.resolve('@hot-loader/react-dom/server'),
'react-dom': require.resolve('@hot-loader/react-dom')
```

Order is important!
