### ISSUE TITLE
Keep getting Uncaught Invariant Violation: Invalid hook call.

### ISSUE THREAD

**Issue by dutzi** [hot-loader/react-dom#20]
Hi,

I keep getting the following error when running the following code:

Uncaught Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons...

-- render.js

```js
import 'react-hot-loader';
import React from 'react';
import ReactDom from 'react-dom';
import App from './components';

export function render(root) {
  ReactDom.render(<App />, root);
}
```

-- components/index.jsx

```js
import { hot } from 'react-hot-loader/root';
import React, { useState } from 'react';

const App = () => {
  const [state, setState] = useState(0);
  return <div>hey</div>;
};

export default hot(App);
```

I'm using React 16.9.0
ReactDOM 16.9.0

React Hot Loader version: 4.12.13

1.  `node -v`: v10.15.1
2.  `npm -v`: 6.4.1

1.  Operating system: macOS 10.14.6
2.  Browser and version: Chrome 76.0.3809.132

**Comment by theKashey** [comment]
Could you please post the beginning of your console output, as long as a provided example tells me nothing.

**Comment by dutzi** [comment]
Of course, and thanks for the quick reply. The entire log is here: https://pastebin.com/UaYfEmbQ

**Comment by theKashey** [comment]
- `webpack-internal:///./node_modules/react`
- `webpack-internal:///../../node_modules/@hot-loader/react-dom`

Why the paths are so different? 

I think this is your problem - at some point in another react-dom was used
> 1. You might have mismatching versions of React and the renderer (such as React DOM)

**Comment by dutzi** [comment]
You're probably right, I tried setting it up again and it worked. (I swear I sanity checked the versions a number of times though!)

The paths are different because it's a Yarn Workspace.

Thank you

**Comment by Bnaya** [comment]
@duti try also using yarn-deduplicate

**Comment by dutzi** [comment]
Thank you, I will!
