### ISSUE TITLE
React v16.10 is out

### ISSUE THREAD

**Issue by Kerumen** [hot-loader/react-dom#21]
https://github.com/facebook/react/releases/tag/v16.10.0

**Comment by Bnaya** [comment]
The patches got broken again
Need to re do them

**Comment by theKashey** [comment]
RHL `4.12.15` released. We could process with `react-dom`

**Comment by Bnaya** [comment]
Go for it :) I don't have publish permissions ;)

**Comment by theKashey** [comment]
🥳 released 🥳, all kudos to @Bnaya

**Comment by davidroeca** [comment]
~Downloaded the latest and this is still not working with:~

```json
{
    "@hot-loader/react-dom": "16.10.2",
    "react": "16.10.2",
    "react-dom": "16.10.2",
    "react-hot-loader": "4.12.15"
}
```

~Using `@hot-loader/react-dom` breaks everything, and switching to `react-dom` works in basic cases.~

**Comment by Bnaya** [comment]
Just tested it on freshly created & ejected CRA project, and works fine

**Comment by davidroeca** [comment]
Yep I think something else is going on with my setup, having trouble reproducing in a simpler case.

**Comment by Bnaya** [comment]
Which errors do you get?

**Comment by davidroeca** [comment]
No errors, just no HMR in my current setup. I actually don't think it's a problem here, but will report back if I find something.

Edit: confirming that this was an issue on my end and has nothing to do with this package.

**Comment by SebastienGllmt** [comment]
[v16.11](https://github.com/facebook/react/releases/tag/v16.11.0)  is out now. Not sure if the new patch has to be made for this

**Comment by theKashey** [comment]
Not the patch, but a new package version - for sure.
