### ISSUE TITLE
It looks like you are run into 'useLayoutEffect does nothing on the server' issue 

### ISSUE THREAD

**Issue by rndm2** [hot-loader/react-dom#29]
The problem is well described in this issue https://github.com/facebook/react/issues/14927#issuecomment-474674179

When using @hot-loader/react-dom/server method renderToString in browser it throw an error 

> Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client

**Comment by theKashey** [comment]
`hot-loader/react-dom` is 100% the original `react-dom` with a few lines changed.
There is no way we could change something in the `react-dom`.
