### ISSUE TITLE
No version available for react-dom 16.12.0

### ISSUE THREAD

**Issue by Donov4n** [hot-loader/react-dom#33]
It seems that there is no available version for react-dom 16.12.0 (released 2 months ago).

**Comment by Vages** [comment]
This prevents React developer tools profiling if you upgrade react to 16.12.0: https://gist.github.com/bvaughn/25e6233aeb1b4f0cdb8d8366e54a3977#tracing-broke-after-an-npm-update

**Comment by ro-savage** [comment]
@theKashey - Any chance on an update?

**Comment by ztoben** [comment]
@theKashey, is this more involved than just running the auto publish util?

**Comment by theKashey** [comment]
@hot-loader/react-dom@16.12.0 has been published

Sorry for a delay, house renovation is able to consume all of you, and all your free time.

**Comment by ksweetie** [comment]
@theKashey I hate to be the bearer of bad news, but React released 16.13.0 one hour after you published 16.12.0 😞Thanks for all your work on this!

**Comment by theKashey** [comment]
Yep, like a two hours after I've released 12 :)
However it's not so easy this time, the existing patch is not working for 16.13 :(

**Comment by theKashey** [comment]
https://github.com/gaearon/react-hot-loader/pull/1428

**Comment by theKashey** [comment]
Update for 16.13 has been released released
