### ISSUE TITLE
No version available for react-dom 16.13.1

### ISSUE THREAD

**Issue by miclud** [hot-loader/react-dom#35]
Hi,
It would be nice if this could be made available as it removes quite a few unnecessary warnings.
https://github.com/facebook/react/releases/tag/v16.13.1

**Comment by theKashey** [comment]
Sorry. Missed this issue.

**Comment by Maxim-Mazurok** [comment]
I was getting same error, but for the different reason.
We use ProGet and unfortunetly it doesn't support `<version core> "+" <build>` format.
It's being discussed here: https://forums.inedo.com/topic/2948/npm-connector-returns-plus-in-versions

**Comment by tomek-f** [comment]
Any updates on this issue?

**Comment by miclud** [comment]
Any update?

**Comment by tomek-f** [comment]
> Any updates on this issue?

**Comment by lzhuor** [comment]
Any update?

**Comment by miclud** [comment]
Closed the issue as new minor version (16.14) has been released
