### ISSUE TITLE
Publish a version for 17 RC

### ISSUE THREAD

**Issue by gaearon** [hot-loader/react-dom#41]
Hi folks, how can we help in publishing a patch for `17.0.0-rc.1`?
We want people to try them but they're blocked by the missing support.

**Comment by theKashey** [comment]
`17.0.0-rc.2+4.13.0` has been published

**Comment by gaearon** [comment]
Yay, thank you!

**Comment by theKashey** [comment]
`17.0.0+4.13.0` joins the club
