### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by etecture-jaleksic** [hot-loader/react-dom#61]
The readme states that `React is MIT licensed. This library is still react`. However, that's quite fuzzy and the lack of an actual MIT license file _in this repository_ makes usage of the library dfficult or impossible in certain scenarios.

A regular license file would be awesome - it doesn't even need a version bump or re-publish.

**Comment by etecture-jaleksic** [comment]
Hm. Weird. The locally installed package _does_ have a license file - indeed the same as react. Is there some magic involved that copies the file when publishing?

**Comment by theKashey** [comment]
"This library" is not the one you use - it derives a copy of react and publishes it, not "self"
See https://unpkg.com/browse/@hot-loader/react-dom@17.0.2/LICENSE

**Comment by etecture-jaleksic** [comment]
I see. The issue for us is that legal department wants a URL to the license file, and typically we provide a URL to the file in the repo.
But I guess in this case the URL you provided is what we need - thanks.
