### ISSUE TITLE
Version 16.8.5

### ISSUE THREAD

**Issue by stnwk** [hot-loader/react-dom#7]
A new day, a new version :)

https://github.com/facebook/react/releases/tag/v16.8.5

**Comment by theKashey** [comment]
Again :( Someone never sleeps

**Comment by stnwk** [comment]
Would be super cool, if there was a way to automate this task 🤔

**Comment by theKashey** [comment]
It's not so easy - first you have to write integrations tests for RHL - https://github.com/gaearon/react-hot-loader/issues/1106
