### ISSUE TITLE
[Suggestion] Automate package publishing

### ISSUE THREAD

**Issue by Bnaya** [hot-loader/react-dom#9]
Followup for:
https://github.com/gaearon/react-hot-loader/issues/1255#issuecomment-495955707

I can write the automation for that, i just want design review:

First, I have failed to find a CI that will let me run builds for NPM package webhooks,
And writing that support for lets say lambci ATM is a big investment.  

So instead of a webhook, we can find a CI with cron jobs, that we can run on a very regular basis(10 minutes?), and query for versions instead of being notified.

Which CI should we use?
If i'm not mistaken, the most frequent Travis can run is only once at day.
So we need something else. i saw that circle CI can run every minute and supports realgar cron syntax. 
I don't have any strong preference. it can be any other good CI

For simplicity i would like to ask collaborator access to this organisation, it will save me handling fork and more configurations.

**Comment by theKashey** [comment]
- once per day is ok
- Travis is great, CircleCI is powerful
- check your mail

And there is one __required__ thing for the automatic publishing - automatic testing using this version of `react-dom`.

**Comment by Bnaya** [comment]
Dose automatic testing means running gaearon/react-hot-loader tests using the newly patched code?

What's the status of the E2E PR?
https://github.com/gaearon/react-hot-loader/pull/1213

Thanks :)

**Comment by theKashey** [comment]
More or less. I was starting doing something like
```js
jest.mock('react-dom', require('hot-loader/react-dom')); // another way to inject it :)

...tests...
```
But majority of tests were failing, as long as they are expecting a _default_ behaviour from `react-dom`.
I am afraid, but we need new tests, not based on enzyme (however e2e is not necessary). To be more concrete - I am a bit tired of the current tests, they all are testing implementation details, and were quite useful during development, but become obsolete years later.

Let's split work into multiple streams:
- automatic updates
- __semi__ automatic publishing.
- renovated tests for hot updating (not for react-hot-loader, but for general, library HMR

**Comment by Bnaya** [comment]
semi automatic publishing: - I think we can publish to `@rc` dist tag automatically,
And the promotion to `@latest ` you can do manually

**Comment by theKashey** [comment]
It's more about matching `react-dom` version. Not sure it's really needed, but __if__ needed, then releases should be mo thoughtful.

**Comment by theKashey** [comment]
I think it's worth looking at https://github.com/gaearon/react/blob/f254e3a1869aa4611feab64b54cc2dca34ab5e58/packages/react-fresh/src/__tests__/ReactFresh-test.js

Probably these tests are portable as-is.

**Comment by theKashey** [comment]
I am introducing some `react-dom`-mocking based tests in https://github.com/gaearon/react-hot-loader/pull/1265
See https://github.com/gaearon/react-hot-loader/blob/ee4604b47be75532d8d82fc8cf21aaece496e19c/test/hot/react-dom.integration.spec.js

**Comment by Bnaya** [comment]
If i follow - https://github.com/gaearon/react-hot-loader/releases
`hot-loader/react-dom` gonna be abandon soon?
Dose the latest code at gaearon/react-hot-loader suppose to work with it?

**Comment by theKashey** [comment]
I was just waiting for someone to report any bug before porting patch here. But a week(or two?) passes and look like it works.

**Comment by Bnaya** [comment]
BTW: I don't have permissions to create circleci project for this repo,
So please create one and give me access :)

**Comment by theKashey** [comment]
> 16.9.0-alpha has been released - https://github.com/hot-loader/react-dom/issues/11, 

another edge case, where we might have alpha versions of something....

**Comment by Bnaya** [comment]
Somewhat done
